-- ============================================================================
-- G-check — carga das rotinas de Gerência (Gerente / Gerente Domingo /
-- Sub Gerente Diurno / Sub Gerente Noturno)
-- ----------------------------------------------------------------------------
-- Gerado a partir das 4 primeiras abas de
-- 'CHECK LIST GERENCIAL ITAPECERICA (APLICATIVO) (1).xlsx' (GERENTE, GERENTE
-- DOMINGO, SUB GERENTE DIURNO, SUB GERENTE NOTURNO). Cada aba = 1 rotina;
-- cada linha da aba = 1 atividade (checklist_items).
--
-- Todas as atividades entram como tipo_tarefa = 'enquete' (opções extraídas
-- da coluna RESPOSTA: SIM/NÃO ou PADRÃO/NÃO PADRÃO). Turno derivado do
-- horário de início (04–11 Manhã · 11–18 Tarde · 18–04 Noite). Anexos
-- (min/max) derivados das colunas FOTO/VIDEO/QUANTIDADE DE FOTO.
--
-- 'GERENTE DOMINGO' é a rotina inteira de domingo: todas as suas atividades
-- ficam com dias_semana = {0}, independente do texto da coluna PERIODO de
-- cada linha (a aba já é, por si só, o checklist específico de domingo).
--
-- Como domingo já é coberto por 'gerente-domingo', as atividades 'DIARIAMENTE'
-- da rotina 'gerente' rodam só de segunda a sábado (dias_semana = {1..6});
-- atividades com dia específico (ex.: TODA TERÇA) não são afetadas, pois já
-- não caíam aos domingos.
--
-- 'SUB GERENTE NOTURNO' atravessa a meia-noite (20:00 → 06:30) — corte_dia
-- em 07:00 evita que o turno resete/trave antes do fim real do expediente.
--
-- responsavel usa o nome EXATO dos profiles já cadastrados no Supabase
-- (liziumaatahyubuywvzy): 'Gerente', 'Sub Gerente Diurno', 'Sub Gerente
-- Noturno' — a rotina 'Gerente Domingo' também usa 'Gerente' (mesmo
-- funcionário, checklist específico de domingo).
--
-- Idempotente: apaga e regrava as 4 rotinas abaixo pelos seus ids.
-- ============================================================================

delete from checklists where id in ('gerente', 'gerente-domingo', 'sub-gerente-diurno', 'sub-gerente-noturno');


-- ----------------------------------------------------------------------------
-- Rotina 'gerente' (82 atividades) — aba 'GERENTE'
-- ----------------------------------------------------------------------------
insert into checklists (id, nome, ativo, reabre_automatico, reabre_intervalo_min, responsavel, corte_dia) values
  ('gerente', 'Rotina completa ''Gerente''', true, false, null, 'Gerente', null);
insert into checklist_items
  (id, checklist_id, titulo, detalhe, status, posicao,
   tipo_tarefa, resposta_opcoes, turno, horario_inicio, horario_termino,
   min_anexos, max_anexos, anexos, recorrencia, dias_semana, inicio)
values
  ('gerente-1', 'gerente', 'TIRAR FOTO DA  ENTRADA NO INICIO DO EXPEDIENTE', null, 'pendente', 1, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '11:00:00', '22:00:00', 1, 1, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-2', 'gerente', 'SEGURANÇA NA LOJA ? NOME DO SEGURANÇAS DO PLANTÃO', 'COLOCAR NOME DOS SEGURANÇAS', 'pendente', 2, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '11:00:00', '11:10:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-3', 'gerente', 'TIRAR FOTO DAS PORTAS FECHADAS NO FINAL DO EXPEDIENTE', null, 'pendente', 3, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '21:30:00', '22:00:00', 2, 2, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-4', 'gerente', 'TEMPERATURA DAS GELADEIRAS', 'tirar foto de todas as geladeiras / Estão com temperatura dentro do padrão ?', 'pendente', 4, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 10, 30, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-5', 'gerente', 'TEMPERATURA DAS ILHAS', 'tirar foto de todas das ilhas / Estão com a temperatura dentro do padrão ?', 'pendente', 5, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 10, 30, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-6', 'gerente', 'TEMPERATURA DAS CAMARAS FRIA', 'tirar foto de todas as camaras frias . Estão com a temperatura dentro do padrão .', 'pendente', 6, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 10, 30, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-7', 'gerente', 'VERIFICAR COMO ESTA O ESTOQUE DA CAMERA FRIA', 'tirar foto de todas as camaras frias . Estão com a temperatura dentro do padrão .', 'pendente', 7, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 10, 30, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-8', 'gerente', 'VERIFICAR CAMARA QUE FICA A PARTE DOS BOIS E PORCOS INTEIRO', 'AS PEÇAS ESTÃO ENCOSTANDO NO CHÃO ?', 'pendente', 8, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-9', 'gerente', 'VERIFICAR PORTAS DO BALCÃO AÇOUGUE E PORTA CAMARA FRIA  ( PARA NÃO CAIR A TEMPERATURA', 'ESTÃO TODAS FECHADAS ?', 'pendente', 9, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '12:00:00', '13:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-10', 'gerente', 'VERIFICAR PORTAS DO BALCÃO AÇOUGUE E PORTA CAMARA FRIA  ( PARA NÃO CAIR A TEMPERATURA', 'ESTÃO TODAS FECHADAS ?', 'pendente', 10, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '16:00:00', '17:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-11', 'gerente', 'VERIFICAR PORTAS DO BALCÃO AÇOUGUE E PORTA CAMARA FRIA  ( PARA NÃO CAIR A TEMPERATURA', 'ESTÃO TODAS FECHADAS ?', 'pendente', 11, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '18:00:00', '19:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-12', 'gerente', 'VERIFICAR PORTAS DO BALCÃO AÇOUGUE E PORTA CAMARA FRIA  ( PARA NÃO CAIR A TEMPERATURA', 'ESTÃO TODAS FECHADAS ?', 'pendente', 12, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '20:00:00', '21:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-13', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CORREDORES', 'ESTA TUDO OK NA RONDA ?', 'pendente', 13, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-14', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CORREDORES', 'ESTA TUDO OK NA RONDA ?', 'pendente', 14, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '16:00:00', '17:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-15', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CORREDORES', 'ESTA TUDO OK NA RONDA ?', 'pendente', 15, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '20:00:00', '21:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-16', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) HORTI FRUTTI ( QUALIDADE , PRECIFICACÃO E ABASTECIMENTO) QUALQUER COISA SINALIZAR NO GRUPO BENAFRUTTI', 'ESTA TUDO OK NA RONDA ?', 'pendente', 16, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-17', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) HORTI FRUTTI ( QUALIDADE , PRECIFICACÃO E ABASTECIMENTO) QUALQUER COISA SINALIZAR NO GRUPO BENAFRUTTI', 'ESTA TUDO OK NA RONDA ?', 'pendente', 17, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '15:00:00', '16:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-18', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) HORTI FRUTTI ( QUALIDADE , PRECIFICACÃO E ABASTECIMENTO) QUALQUER COISA SINALIZAR NO GRUPO BENAFRUTTI', 'ESTA TUDO OK NA RONDA ?', 'pendente', 18, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '18:00:00', '19:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-19', 'gerente', 'VERIFICAR PRODUÇÃO BENAFRUTTI , ABASTECIMENTO GELADEIRA E VALIDADE', 'ESTA BEM ABASTECIDO ? PRODUÇÃO DENTRO DOS CONFORMES? VALIDADE OK ?', 'pendente', 19, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-20', 'gerente', 'VERIFICAR PRODUÇÃO BENAFRUTTI , ABASTECIMENTO GELADEIRA E VALIDADE', 'ESTA BEM ABASTECIDO ? PRODUÇÃO DENTRO DOS CONFORMES? VALIDADE OK ?', 'pendente', 20, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '15:00:00', '16:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-21', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PERECIVEIS ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 21, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-22', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PERECIVEIS ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 22, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '16:00:00', '17:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-23', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PERECIVEIS ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 23, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '20:00:00', '21:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-24', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PADARIA PRODUÇÃO , PRECIFICAÇÃO , LIMPEZA  E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 24, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-25', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PADARIA PRODUÇÃO , PRECIFICAÇÃO , LIMPEZA  E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 25, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '15:00:00', '16:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-26', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PADARIA PRODUÇÃO , PRECIFICAÇÃO , LIMPEZA  E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 26, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '20:00:00', '21:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-27', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) AÇOUGUE  ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 27, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-28', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) AÇOUGUE  ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 28, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '16:00:00', '17:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-29', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) AÇOUGUE  ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 29, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '20:00:00', '21:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-30', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CAMARA FRIA CARRINHOS , GIRO DE FUNCIONARIOS NÃO PERMITIDOS , ORGANIZAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 30, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-31', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CAMARA FRIA CARRINHOS , GIRO DE FUNCIONARIOS NÃO PERMITIDOS , ORGANIZAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 31, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '16:00:00', '17:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-32', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CAMARA FRIA CARRINHOS , GIRO DE FUNCIONARIOS NÃO PERMITIDOS , ORGANIZAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 32, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '18:00:00', '19:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-33', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) ESTOQUE ORGANIZAÇÃO E SE TODOS OS PRODUTOS ESTAO NA AREA DE VENDA', 'ESTA TUDO OK NA RONDA ?', 'pendente', 33, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-34', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) ESTOQUE ORGANIZAÇÃO E SE TODOS OS PRODUTOS ESTAO NA AREA DE VENDA', 'ESTA TUDO OK NA RONDA ?', 'pendente', 34, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-35', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) TROCA ORGANIZADAS ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 35, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-36', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) TROCA ORGANIZADAS ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 36, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-37', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) ESTACIONAMENTO SEM CARRINHOS E CARROS DE FUNCIONARIOS ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 37, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-38', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) ESTACIONAMENTO SEM CARRINHOS E CARROS DE FUNCIONARIOS ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 38, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:20:00', '13:40:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-39', 'gerente', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) REFEITORIO / VESTIARIO ORGANIZADO ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 39, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:30:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-40', 'gerente', 'GELADEIRAS ( SEM SACOLAS E PRODUTOS QUE POSSAM CONTAMILAR AS MARMITAS ) ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 40, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '14:00:00', '15:00:00', 5, 15, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-41', 'gerente', 'VERIFICAR TODOS OS CONSULTA PREÇO', '1 FOTO DO TESTE OK  E 1 FOTO DO LOCAL QUE ESTA', 'pendente', 41, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:30:00', 10, 20, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-42', 'gerente', 'VERIFICAR TODOS OS CONSULTA PREÇO', '1 FOTO DO TESTE OK  E 1 FOTO DO LOCAL QUE ESTA', 'pendente', 42, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '19:00:00', '20:00:00', 10, 20, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-43', 'gerente', 'PLACA DE SINALIZAÇÃO ( SE ESTA TUDO OK )', null, 'pendente', 43, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '11:00:00', '22:00:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-44', 'gerente', 'HORARIO ALMOÇO', '1 INICIO E 1 NO TERMINO', 'pendente', 44, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '15:00:00', '16:00:00', 2, 2, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-45', 'gerente', 'PAUSA CAFÉ', '1 INICIO E 1 NO TERMINO', 'pendente', 45, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '19:00:00', '19:30:00', 2, 2, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-46', 'gerente', 'VERIFICAR PRECIFICAÇÃO DIA ANTERIOR ( TERÇA E QUARTA VERDE ? )', 'FOTO DE TODAS AS PLACAS', 'pendente', 46, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '21:00:00', '22:00:00', 10, 20, '[]'::jsonb, 'semanal', '{2}', null),
  ('gerente-47', 'gerente', 'VERIFICAR PRECIFICAÇÃO DIA ANTERIOR ( QUINTA DA LIMPEZA ?)', 'FOTO DE TODAS AS PLACAS', 'pendente', 47, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '21:00:00', '22:00:00', 10, 20, '[]'::jsonb, 'semanal', '{3}', null),
  ('gerente-48', 'gerente', 'VERIFICAR PRECIFICAÇÃO DIA ANTERIOR ( SEXTA LANCHE ? )', 'FOTO DE TODAS AS PLACAS', 'pendente', 48, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '21:00:00', '22:00:00', 10, 20, '[]'::jsonb, 'semanal', '{4}', null),
  ('gerente-49', 'gerente', 'VERIFICAR AS PRECIFICAÇÕES DO TABLOIDE DIA ANTERIOR ( SEXTA , SABADO E DOMINGO )', 'FOTO DE TODAS AS PLACAS', 'pendente', 49, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '21:00:00', '22:00:00', 20, 50, '[]'::jsonb, 'semanal', '{4}', null),
  ('gerente-50', 'gerente', 'VERIFICAR SE O TIME ESTA COM O TABLOIDE DE OFERTAS DO DIA SEGUINTE PARA INTENSIFICAR O ABASTECIMENTO E PONTOS EXTRAS', 'FOI ENTREGUE O TABLOIDE OU LISTAGEM PARA TODA LIDERANÇA ?', 'pendente', 50, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '11:00:00', '22:00:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-51', 'gerente', 'PONTO EXTRA ( AÇÕES SEXTA A DOMINGO )', 'FOTO DOS PONTO EXTRA', 'pendente', 51, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '11:00:00', '22:00:00', 1, 10, '[]'::jsonb, 'semanal', '{4}', null),
  ('gerente-52', 'gerente', 'CONTROLE DE MARGEM DE VENDA', 'COMUNICAR COMERCIAL ( ESTANDO ALGO INRREGULAR)', 'pendente', 52, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 1, 1, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-53', 'gerente', 'CONTROLAR TANQUE GERADOR', 'ENVIAR FOTO NA GERENCIA', 'pendente', 53, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '16:00:00', '17:00:00', 1, 1, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-54', 'gerente', 'CONTROLAR MOTORES DAS GELADEIRAS EM GERAL', 'ENVIAR FOTO NA GERENCIA', 'pendente', 54, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '14:00:00', '15:00:00', 1, 10, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-55', 'gerente', 'SOLICITAR RETIRADAS DE CARRINHAS DO ESTACIONAMENTO E FRENTE DE LOJA', 'NOME DO COLABORADOR SOLICITADO PARA A RETIRA DOS CARRINHOS , FAZER  GIRO', 'pendente', 55, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-56', 'gerente', 'SOLICITAR RETIRADAS DE CARRINHAS DO ESTACIONAMENTO E FRENTE DE LOJA', 'NOME DO COLABORADOR SOLICITADO PARA A RETIRA DOS CARRINHOS , FAZER  GIRO', 'pendente', 56, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '14:00:00', '15:00:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-57', 'gerente', 'SOLICITAR RETIRADAS DE CARRINHAS DO ESTACIONAMENTO E FRENTE DE LOJA', 'NOME DO COLABORADOR SOLICITADO PARA A RETIRA DOS CARRINHOS , FAZER  GIRO', 'pendente', 57, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-58', 'gerente', 'SOLICITAR RETIRADAS DE CARRINHAS DO ESTACIONAMENTO E FRENTE DE LOJA', 'NOME DO COLABORADOR SOLICITADO PARA A RETIRA DOS CARRINHOS , FAZER  GIRO', 'pendente', 58, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '19:00:00', '20:00:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-59', 'gerente', 'SOLICITAR RETIRADAS DE CARRINHAS DO ESTACIONAMENTO E FRENTE DE LOJA', 'NOME DO COLABORADOR SOLICITADO PARA A RETIRA DOS CARRINHOS , FAZER  GIRO', 'pendente', 59, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '20:00:00', '21:30:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-60', 'gerente', 'VERIFICAR ESTOQUE DOS AEREOS SE ESTÃO DATADOS E ORGANIADOS', 'ESTA TUDO DENTRO DOS CONFORMES ?', 'pendente', 60, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '11:00:00', '22:00:00', 10, 20, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-61', 'gerente', 'VERIFICAÇÃO DE UTILIZAÇÃO DE TOCA , LUVA E EPIS NA PADARIA ( PESSOAL DA TARDE )', 'TUDO OK ?', 'pendente', 61, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:10:00', '14:10:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-62', 'gerente', 'VERIFICAÇÃO DE LIMPEZA DOS UNIFORMES DA PADARIA  ( PESSOAL DA TARDE )', 'TUDO OK ?', 'pendente', 62, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:10:00', '14:10:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-63', 'gerente', 'VERIFICAÇÃO DE UTILIZAÇÃO DE TOCA, LUVA E EPIS AÇOUGUE  ( PESSOAL DA TARDE )', 'TUDO OK ?', 'pendente', 63, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:10:00', '14:10:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-64', 'gerente', 'VERIFICAÇÃO DE LIMPEZA DOS UNIFORMES AÇOUGUE ( PESSOAL DA TARDE )', 'TUDO OK ?', 'pendente', 64, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:10:00', '14:10:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-65', 'gerente', 'BATIDA DE VALIDADE EM TODOS OS SETORES ( FAZER ACOMPANHAMENTO )', 'TUDO OK ?  ALGUM PRODUTO VENCIDO ?', 'pendente', 65, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '22:00:00', 0, null, '[]'::jsonb, 'semanal', '{2}', null),
  ('gerente-66', 'gerente', 'BATIDA DE PRECIFICAÇÃO EM TODOS OS SETORES ( FAZER ACOMPANHAMENTO )', 'TUDO OK ? ALGUMA DISCRIÇÃO ERRADA ? ALGUM PREÇO ERRADO ?', 'pendente', 66, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '22:00:00', 0, null, '[]'::jsonb, 'semanal', '{4}', null),
  ('gerente-67', 'gerente', 'ACOMPANHAR GRUPO DE RECEBIMENTO PARA MERCADORIA NÃO FICAR PARADA NO ESTOQUE', null, 'pendente', 67, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '22:00:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-68', 'gerente', 'VERIFICAR SE O TIME DE SEGURANÇA ESTA FAZENDO A ROTINA CORRETA PARA PREVENÇÃO DE FURTO E ROUBO ( CHECK LIST E GRUPO NO WHATSAAP ).', null, 'pendente', 68, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '22:00:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-69', 'gerente', 'VERIFICAR LIMPEZA DOS BANHEIROS', 'ESTA BEM LIMPO ? ESTAO SEGUINDO A ESCALA ?', 'pendente', 69, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 2, 10, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-70', 'gerente', 'VERIFICAR LIMPEZA DOS BANHEIROS', 'ESTA BEM LIMPO ? ESTAO SEGUINDO A ESCALA ?', 'pendente', 70, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 2, 10, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-71', 'gerente', 'VERIFICAR LIMPEZA DOS BANHEIROS', 'ESTA BEM LIMPO ? ESTAO SEGUINDO A ESCALA ?', 'pendente', 71, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '20:30:00', '21:30:00', 2, 10, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-72', 'gerente', 'VERIFICAR LIMPEZA DA LOJA', 'ESTA BEM LIMPA ? ESTÃO SEGUINDO A ESCALA ?', 'pendente', 72, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '13:00:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-73', 'gerente', 'VERIFICAR LIMPEZA DA LOJA', 'ESTA BEM LIMPA ? ESTÃO SEGUINDO A ESCALA ?', 'pendente', 73, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '19:00:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-74', 'gerente', 'VERIFICAR EXTINTORES ( VALIDADE , LACRE, LOCALIZAÇÃO ( DEIXAR SEMPRE LIVRE )', null, 'pendente', 74, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '19:00:00', '20:00:00', 0, null, '[]'::jsonb, 'mensal', '{}', '2026-09-10'),
  ('gerente-75', 'gerente', 'VERIFICAR SE O SUB GERENTE MANHÃ TIROU O RELATORIO DE MERCADORIA RECEBIDA DO DIA ANTERIOR E REPASSOU', 'TODAS AS MERCADORIAS ESTÃO NA AREA DE VENDA ?', 'pendente', 75, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '22:00:00', 1, 2, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-76', 'gerente', 'VERIFICAR SE O SUB GERENTE MANHÃ FEZ A CONFERENCIA DO FUNDO DE TROCO DAS FISCAIS', 'SE SIM NOME DAS FISCAIS QUE FOI FEITA A CONFERENCIA', 'pendente', 76, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '22:00:00', 0, null, '[]'::jsonb, 'semanal', '{5}', null),
  ('gerente-77', 'gerente', 'CEBO DO AÇOUGUE ESTA SENDO RETIRADO ?', 'CASO NÃO ESTEJA AVISAR GERENTE JULIANA', 'pendente', 77, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '22:00:00', 1, 5, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-78', 'gerente', 'OS PAPELÕES E EMBALAGENS ESTÃO SENDO RETIRADOS ?', 'CASO NÃO ESTEJA AVISAR GERENTE JULIANA', 'pendente', 78, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '22:00:00', 1, 5, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-79', 'gerente', 'CONTROLE DE PRAGAS', 'ENVIAR DOCUMENTO PARA GERENTE JULIANA', 'pendente', 79, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '11:00:00', '22:00:00', 1, 5, '[]'::jsonb, 'mensal', '{}', '2026-09-15'),
  ('gerente-80', 'gerente', 'EPIS ( HORARIO TARDE ) TODOS OS COLABORADORES ESTÃO OK ?', 'ESTÃO MARCANDO NO CONTROLE EPIS ?', 'pendente', 80, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:10:00', '14:00:00', 1, 5, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-81', 'gerente', 'VENDAS FRENTE CAIXA ?', 'ESTÃO OFERENCENDO OS PRODUTOS ?', 'pendente', 81, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '22:00:00', 1, 5, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null),
  ('gerente-82', 'gerente', 'ESTÃO CONTROLANDO HORA EXTRA ? CASO PASSE DE 2 HORAS . PROGRAMAR PARA 2 HORAS E 15', '15 MINUTOS DE PAUSA BATIDA NO PONTO , FORNECER KIT HORA EXTRA PARA LANCHE', 'pendente', 82, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '11:00:00', '22:00:00', 0, null, '[]'::jsonb, 'semanal', '{1,2,3,4,5,6}', null);


-- ----------------------------------------------------------------------------
-- Rotina 'gerente-domingo' (63 atividades) — aba 'GERENTE DOMINGO'
-- ----------------------------------------------------------------------------
insert into checklists (id, nome, ativo, reabre_automatico, reabre_intervalo_min, responsavel, corte_dia) values
  ('gerente-domingo', 'Rotina completa ''Gerente Domingo''', true, false, null, 'Gerente', null);
insert into checklist_items
  (id, checklist_id, titulo, detalhe, status, posicao,
   tipo_tarefa, resposta_opcoes, turno, horario_inicio, horario_termino,
   min_anexos, max_anexos, anexos, recorrencia, dias_semana, inicio)
values
  ('gerente-domingo-1', 'gerente-domingo', 'TIRAR FOTO DA  ENTRADA NO INICIO DO EXPEDIENTE', null, 'pendente', 1, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '07:00:00', '07:40:00', 1, 1, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-2', 'gerente-domingo', 'SEGURANÇA NA LOJA ? NOME DO SEGURANÇAS DO PLANTÃO', 'COLOCAR NOME DOS SEGURANÇAS', 'pendente', 2, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '07:00:00', '08:00:00', 0, null, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-3', 'gerente-domingo', 'TIRAR FOTO DAS PORTAS FECHADAS NO FINAL DO EXPEDIENTE', null, 'pendente', 3, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '18:30:00', '20:00:00', 2, 2, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-4', 'gerente-domingo', 'TEMPERATURA DAS GELADEIRAS', 'tirar foto de todas as geladeiras / Estão com temperatura dentro do padrão ?', 'pendente', 4, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:00:00', 10, 30, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-5', 'gerente-domingo', 'TEMPERATURA DAS ILHAS', 'tirar foto de todas das ilhas / Estão com a temperatura dentro do padrão ?', 'pendente', 5, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:00:00', 10, 30, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-6', 'gerente-domingo', 'TEMPERATURA DAS CAMARAS FRIA', 'tirar foto de todas as camaras frias . Estão com a temperatura dentro do padrão .', 'pendente', 6, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:00:00', 10, 30, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-7', 'gerente-domingo', 'VERIFICAR COMO ESTA O ESTOQUE DA CAMERA FRIA', 'tirar foto de todas as camaras frias . Estão com a temperatura dentro do padrão .', 'pendente', 7, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:00:00', 10, 30, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-8', 'gerente-domingo', 'VERIFICAR CAMARA QUE FICA A PARTE DOS BOIS E PORCOS INTEIRO', 'AS PEÇAS ESTÃO ENCOSTANDO NO CHÃO ?', 'pendente', 8, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-9', 'gerente-domingo', 'VERIFICAR PORTAS DO BALCÃO AÇOUGUE E PORTA CAMARA FRIA  ( PARA NÃO CAIR A TEMPERATURA', 'ESTÃO TODAS FECHADAS ?', 'pendente', 9, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '09:00:00', '10:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-10', 'gerente-domingo', 'VERIFICAR PORTAS DO BALCÃO AÇOUGUE E PORTA CAMARA FRIA  ( PARA NÃO CAIR A TEMPERATURA', 'ESTÃO TODAS FECHADAS ?', 'pendente', 10, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-11', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CORREDORES', 'ESTA TUDO OK NA RONDA ?', 'pendente', 11, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-12', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CORREDORES', 'ESTA TUDO OK NA RONDA ?', 'pendente', 12, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-13', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CORREDORES', 'ESTA TUDO OK NA RONDA ?', 'pendente', 13, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-14', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) HORTI FRUTTI ( QUALIDADE , PRECIFICACÃO E ABASTECIMENTO) QUALQUER COISA SINALIZAR NO GRUPO BENAFRUTTI', 'ESTA TUDO OK NA RONDA ?', 'pendente', 14, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-15', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) HORTI FRUTTI ( QUALIDADE , PRECIFICACÃO E ABASTECIMENTO) QUALQUER COISA SINALIZAR NO GRUPO BENAFRUTTI', 'ESTA TUDO OK NA RONDA ?', 'pendente', 15, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-16', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) HORTI FRUTTI ( QUALIDADE , PRECIFICACÃO E ABASTECIMENTO) QUALQUER COISA SINALIZAR NO GRUPO BENAFRUTTI', 'ESTA TUDO OK NA RONDA ?', 'pendente', 16, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-17', 'gerente-domingo', 'VERIFICAR PRODUÇÃO BENAFRUTTI , ABASTECIMENTO GELADEIRA E VALIDADE', 'ESTA BEM ABASTECIDO ? PRODUÇÃO DENTRO DOS CONFORMES? VALIDADE OK ?', 'pendente', 17, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '09:00:00', '10:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-18', 'gerente-domingo', 'VERIFICAR PRODUÇÃO BENAFRUTTI , ABASTECIMENTO GELADEIRA E VALIDADE', 'ESTA BEM ABASTECIDO ? PRODUÇÃO DENTRO DOS CONFORMES? VALIDADE OK ?', 'pendente', 18, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-19', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PERECIVEIS ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 19, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-20', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PERECIVEIS ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 20, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-21', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PERECIVEIS ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 21, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-22', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PADARIA PRODUÇÃO , PRECIFICAÇÃO , LIMPEZA  E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 22, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-23', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PADARIA PRODUÇÃO , PRECIFICAÇÃO , LIMPEZA  E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 23, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-24', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PADARIA PRODUÇÃO , PRECIFICAÇÃO , LIMPEZA  E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 24, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-25', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) AÇOUGUE  ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 25, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-26', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) AÇOUGUE  ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 26, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-27', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) AÇOUGUE  ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 27, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-28', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CAMARA FRIA CARRINHOS , GIRO DE FUNCIONARIOS NÃO PERMITIDOS , ORGANIZAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 28, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-29', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CAMARA FRIA CARRINHOS , GIRO DE FUNCIONARIOS NÃO PERMITIDOS , ORGANIZAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 29, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-30', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CAMARA FRIA CARRINHOS , GIRO DE FUNCIONARIOS NÃO PERMITIDOS , ORGANIZAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 30, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-31', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) ESTOQUE ORGANIZAÇÃO E SE TODOS OS PRODUTOS ESTAO NA AREA DE VENDA', 'ESTA TUDO OK NA RONDA ?', 'pendente', 31, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-32', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) ESTOQUE ORGANIZAÇÃO E SE TODOS OS PRODUTOS ESTAO NA AREA DE VENDA', 'ESTA TUDO OK NA RONDA ?', 'pendente', 32, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '14:00:00', '15:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-33', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) TROCA ORGANIZADAS ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 33, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-34', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) TROCA ORGANIZADAS ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 34, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '14:00:00', '15:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-35', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) ESTACIONAMENTO SEM CARRINHOS E CARROS DE FUNCIONARIOS ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 35, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '09:00:00', '10:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-36', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) ESTACIONAMENTO SEM CARRINHOS E CARROS DE FUNCIONARIOS ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 36, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-37', 'gerente-domingo', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) REFEITORIO / VESTIARIO ORGANIZADO ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 37, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '10:00:00', '11:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-38', 'gerente-domingo', 'GELADEIRAS ( SEM SACOLAS E PRODUTOS QUE POSSAM CONTAMILAR AS MARMITAS ) ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 38, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '10:00:00', '11:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-39', 'gerente-domingo', 'VERIFICAR TODOS OS CONSULTA PREÇO', '1 FOTO DO TESTE OK  E 1 FOTO DO LOCAL QUE ESTA', 'pendente', 39, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:30:00', '08:30:00', 10, 20, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-40', 'gerente-domingo', 'VERIFICAR TODOS OS CONSULTA PREÇO', '1 FOTO DO TESTE OK  E 1 FOTO DO LOCAL QUE ESTA', 'pendente', 40, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 10, 20, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-41', 'gerente-domingo', 'HORARIO ALMOÇO', '1 INICIO E 1 NO TERMINO', 'pendente', 41, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '12:00:00', '13:00:00', 2, 2, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-42', 'gerente-domingo', 'PAUSA CAFÉ', '1 INICIO E 1 NO TERMINO', 'pendente', 42, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '16:00:00', '16:30:00', 2, 2, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-43', 'gerente-domingo', 'VERIFICAR PRECIFICAÇÃO DIA ANTERIOR ( OFERTA SEGUNDA FENOMENAL )', 'FOTO DE TODAS AS PLACAS  COLOCADA DA SEGUNDA FENOMENAL', 'pendente', 43, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '18:00:00', '19:00:00', 10, 20, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-44', 'gerente-domingo', 'VERIFICAR AS PRECIFICAÇÕES DO TABLOIDE ( SEGUNDA A QUINTA )', 'FOTO DE TODAS AS PLACAS', 'pendente', 44, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '18:00:00', '20:00:00', 20, 50, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-45', 'gerente-domingo', 'PONTO EXTRA ( AÇÕES SEGUNDA A QUINTA )', 'FOTO DOS PONTO EXTRA', 'pendente', 45, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '08:00:00', '18:00:00', 1, 10, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-46', 'gerente-domingo', 'CONTROLE DE MARGEM DE VENDA', 'COMUNICAR COMERCIAL ( ESTANDO ALGO INRREGULAR)', 'pendente', 46, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '10:00:00', '11:00:00', 1, 1, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-47', 'gerente-domingo', 'CONTROLE DE MARGEM DE VENDA', 'COMUNICAR COMERCIAL ( ESTANDO ALGO INRREGULAR)', 'pendente', 47, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '14:00:00', '15:00:00', 1, 1, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-48', 'gerente-domingo', 'CONTROLAR MOTORES DAS GELADEIRAS EM GERAL', 'ENVIAR FOTO NA GERENCIA', 'pendente', 48, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 1, 10, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-49', 'gerente-domingo', 'SOLICITAR RETIRADAS DE CARRINHAS DO ESTACIONAMENTO E FRENTE DE LOJA', 'NOME DO COLABORADOR SOLICITADO PARA A RETIRA DOS CARRINHOS , FAZER  GIRO', 'pendente', 49, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '09:00:00', '10:00:00', 0, null, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-50', 'gerente-domingo', 'SOLICITAR RETIRADAS DE CARRINHAS DO ESTACIONAMENTO E FRENTE DE LOJA', 'NOME DO COLABORADOR SOLICITADO PARA A RETIRA DOS CARRINHOS , FAZER  GIRO', 'pendente', 50, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 0, null, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-51', 'gerente-domingo', 'SOLICITAR RETIRADAS DE CARRINHAS DO ESTACIONAMENTO E FRENTE DE LOJA', 'NOME DO COLABORADOR SOLICITADO PARA A RETIRA DOS CARRINHOS , FAZER  GIRO', 'pendente', 51, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 0, null, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-52', 'gerente-domingo', 'SOLICITAR RETIRADAS DE CARRINHAS DO ESTACIONAMENTO E FRENTE DE LOJA', 'NOME DO COLABORADOR SOLICITADO PARA A RETIRA DOS CARRINHOS , FAZER  GIRO', 'pendente', 52, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '15:00:00', '16:00:00', 0, null, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-53', 'gerente-domingo', 'SOLICITAR RETIRADAS DE CARRINHAS DO ESTACIONAMENTO E FRENTE DE LOJA', 'NOME DO COLABORADOR SOLICITADO PARA A RETIRA DOS CARRINHOS , FAZER  GIRO', 'pendente', 53, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '17:00:00', '18:30:00', 0, null, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-54', 'gerente-domingo', 'VERIFICAÇÃO DE UTILIZAÇÃO DE TOCA , LUVA E EPIS NA PADARIA ( PESSOAL DA TARDE )', 'TUDO OK ?', 'pendente', 54, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:30:00', '10:00:00', 0, null, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-55', 'gerente-domingo', 'VERIFICAÇÃO DE LIMPEZA DOS UNIFORMES DA PADARIA  ( PESSOAL DA TARDE )', 'TUDO OK ?', 'pendente', 55, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:30:00', '10:00:00', 0, null, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-56', 'gerente-domingo', 'VERIFICAÇÃO DE UTILIZAÇÃO DE TOCA, LUVA E EPIS AÇOUGUE  ( PESSOAL DA TARDE )', 'TUDO OK ?', 'pendente', 56, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:30:00', '10:00:00', 0, null, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-57', 'gerente-domingo', 'VERIFICAÇÃO DE LIMPEZA DOS UNIFORMES AÇOUGUE ( PESSOAL DA TARDE )', 'TUDO OK ?', 'pendente', 57, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:30:00', '10:00:00', 0, null, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-58', 'gerente-domingo', 'VERIFICAR LIMPEZA DOS BANHEIROS', 'ESTA BEM LIMPO ? ESTAO SEGUINDO A ESCALA ?', 'pendente', 58, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:30:00', 2, 10, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-59', 'gerente-domingo', 'VERIFICAR LIMPEZA DOS BANHEIROS', 'ESTA BEM LIMPO ? ESTAO SEGUINDO A ESCALA ?', 'pendente', 59, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '10:00:00', '11:00:00', 2, 10, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-60', 'gerente-domingo', 'VERIFICAR LIMPEZA DOS BANHEIROS', 'ESTA BEM LIMPO ? ESTAO SEGUINDO A ESCALA ?', 'pendente', 60, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '15:00:00', '16:00:00', 2, 10, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-61', 'gerente-domingo', 'VERIFICAR LIMPEZA DOS BANHEIROS', 'ESTA BEM LIMPO ? ESTAO SEGUINDO A ESCALA ?', 'pendente', 61, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:30:00', '18:30:00', 2, 10, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-62', 'gerente-domingo', 'VERIFICAR LIMPEZA DA LOJA', 'ESTA BEM LIMPA ? ESTÃO SEGUINDO A ESCALA ?', 'pendente', 62, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '09:00:00', '10:00:00', 0, null, '[]'::jsonb, 'semanal', '{0}', null),
  ('gerente-domingo-63', 'gerente-domingo', 'VERIFICAR LIMPEZA DA LOJA', 'ESTA BEM LIMPA ? ESTÃO SEGUINDO A ESCALA ?', 'pendente', 63, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '14:00:00', '15:00:00', 0, null, '[]'::jsonb, 'semanal', '{0}', null);


-- ----------------------------------------------------------------------------
-- Rotina 'sub-gerente-diurno' (81 atividades) — aba 'SUB GERENTE DIURNO'
-- ----------------------------------------------------------------------------
insert into checklists (id, nome, ativo, reabre_automatico, reabre_intervalo_min, responsavel, corte_dia) values
  ('sub-gerente-diurno', 'Rotina completa ''Sub Gerente Diurno''', true, false, null, 'Sub Gerente Diurno', null);
insert into checklist_items
  (id, checklist_id, titulo, detalhe, status, posicao,
   tipo_tarefa, resposta_opcoes, turno, horario_inicio, horario_termino,
   min_anexos, max_anexos, anexos, recorrencia, dias_semana, inicio)
values
  ('sub-gerente-diurno-1', 'sub-gerente-diurno', 'TIRAR FOTO DA  ENTRADA NO INICIO DO EXPEDIENTE', null, 'pendente', 1, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '07:00:00', '07:40:00', 1, 1, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-2', 'sub-gerente-diurno', 'SEGURANÇA NA LOJA ? NOME DO SEGURANÇAS DO PLANTÃO', 'COLOCAR NOME DOS SEGURANÇAS', 'pendente', 2, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '07:00:00', '08:00:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-3', 'sub-gerente-diurno', 'TIRAR FOTO DAS PORTAS FECHADAS NO FINAL DO EXPEDIENTE', null, 'pendente', 3, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '18:30:00', '20:00:00', 2, 2, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-4', 'sub-gerente-diurno', 'TEMPERATURA DAS GELADEIRAS', 'tirar foto de todas as geladeiras / Estão com temperatura dentro do padrão ?', 'pendente', 4, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:00:00', 10, 30, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-5', 'sub-gerente-diurno', 'TEMPERATURA DAS ILHAS', 'tirar foto de todas das ilhas / Estão com a temperatura dentro do padrão ?', 'pendente', 5, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:30:00', 10, 30, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-6', 'sub-gerente-diurno', 'TEMPERATURA DAS CAMARAS FRIA', 'tirar foto de todas as camaras frias . Estão com a temperatura dentro do padrão .', 'pendente', 6, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:30:00', 10, 30, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-7', 'sub-gerente-diurno', 'VERIFICAR COMO ESTA O ESTOQUE DA CAMERA FRIA', 'tirar foto de todas as camaras frias . Estão com a temperatura dentro do padrão .', 'pendente', 7, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:30:00', 10, 30, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-8', 'sub-gerente-diurno', 'VERIFICAR CAMARA QUE FICA A PARTE DOS BOIS E PORCOS INTEIRO', 'AS PEÇAS ESTÃO ENCOSTANDO NO CHÃO ?', 'pendente', 8, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:30:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-9', 'sub-gerente-diurno', 'VERIFICAR PORTAS DO BALCÃO AÇOUGUE E PORTA CAMARA FRIA  ( PARA NÃO CAIR A TEMPERATURA', 'ESTÃO TODAS FECHADAS ?', 'pendente', 9, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:30:00', '09:30:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-10', 'sub-gerente-diurno', 'VERIFICAR PORTAS DO BALCÃO AÇOUGUE E PORTA CAMARA FRIA  ( PARA NÃO CAIR A TEMPERATURA', 'ESTÃO TODAS FECHADAS ?', 'pendente', 10, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '12:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-11', 'sub-gerente-diurno', 'VERIFICAR PORTAS DO BALCÃO AÇOUGUE E PORTA CAMARA FRIA  ( PARA NÃO CAIR A TEMPERATURA', 'ESTÃO TODAS FECHADAS ?', 'pendente', 11, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-12', 'sub-gerente-diurno', 'VERIFICAR PORTAS DO BALCÃO AÇOUGUE E PORTA CAMARA FRIA  ( PARA NÃO CAIR A TEMPERATURA', 'ESTÃO TODAS FECHADAS ?', 'pendente', 12, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '15:00:00', '16:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-13', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CORREDORES', 'ESTA TUDO OK NA RONDA ?', 'pendente', 13, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-14', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CORREDORES', 'ESTA TUDO OK NA RONDA ?', 'pendente', 14, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-15', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CORREDORES', 'ESTA TUDO OK NA RONDA ?', 'pendente', 15, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-16', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) HORTI FRUTTI ( QUALIDADE , PRECIFICACÃO E ABASTECIMENTO) QUALQUER COISA SINALIZAR NO GRUPO BENAFRUTTI', 'ESTA TUDO OK NA RONDA ?', 'pendente', 16, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-17', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) HORTI FRUTTI ( QUALIDADE , PRECIFICACÃO E ABASTECIMENTO) QUALQUER COISA SINALIZAR NO GRUPO BENAFRUTTI', 'ESTA TUDO OK NA RONDA ?', 'pendente', 17, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-18', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) HORTI FRUTTI ( QUALIDADE , PRECIFICACÃO E ABASTECIMENTO) QUALQUER COISA SINALIZAR NO GRUPO BENAFRUTTI', 'ESTA TUDO OK NA RONDA ?', 'pendente', 18, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-19', 'sub-gerente-diurno', 'VERIFICAR PRODUÇÃO BENAFRUTTI , ABASTECIMENTO GELADEIRA E VALIDADE', 'ESTA BEM ABASTECIDO ? PRODUÇÃO DENTRO DOS CONFORMES? VALIDADE OK ?', 'pendente', 19, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '09:00:00', '10:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-20', 'sub-gerente-diurno', 'VERIFICAR PRODUÇÃO BENAFRUTTI , ABASTECIMENTO GELADEIRA E VALIDADE', 'ESTA BEM ABASTECIDO ? PRODUÇÃO DENTRO DOS CONFORMES? VALIDADE OK ?', 'pendente', 20, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-21', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PERECIVEIS ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 21, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-22', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PERECIVEIS ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 22, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-23', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PERECIVEIS ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 23, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-24', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PADARIA PRODUÇÃO , PRECIFICAÇÃO , LIMPEZA  E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 24, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-25', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PADARIA PRODUÇÃO , PRECIFICAÇÃO , LIMPEZA  E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 25, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-26', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) PADARIA PRODUÇÃO , PRECIFICAÇÃO , LIMPEZA  E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 26, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-27', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) AÇOUGUE  ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 27, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-28', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) AÇOUGUE  ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 28, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-29', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) AÇOUGUE  ABASTECIMENTO , PRECIFICAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 29, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-30', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CAMARA FRIA CARRINHOS , GIRO DE FUNCIONARIOS NÃO PERMITIDOS , ORGANIZAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 30, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-31', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CAMARA FRIA CARRINHOS , GIRO DE FUNCIONARIOS NÃO PERMITIDOS , ORGANIZAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 31, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-32', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) CAMARA FRIA CARRINHOS , GIRO DE FUNCIONARIOS NÃO PERMITIDOS , ORGANIZAÇÃO , LIMPEZA E VALIDADE', 'ESTA TUDO OK NA RONDA ?', 'pendente', 32, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '17:00:00', '18:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-33', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) ESTOQUE ORGANIZAÇÃO E SE TODOS OS PRODUTOS ESTAO NA AREA DE VENDA', 'ESTA TUDO OK NA RONDA ?', 'pendente', 33, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-34', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) ESTOQUE ORGANIZAÇÃO E SE TODOS OS PRODUTOS ESTAO NA AREA DE VENDA', 'ESTA TUDO OK NA RONDA ?', 'pendente', 34, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-35', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) TROCA ORGANIZADAS ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 35, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-36', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) TROCA ORGANIZADAS ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 36, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-37', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) ESTACIONAMENTO SEM CARRINHOS E CARROS DE FUNCIONARIOS ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 37, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '09:00:00', '10:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-38', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) ESTACIONAMENTO SEM CARRINHOS E CARROS DE FUNCIONARIOS ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 38, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '15:00:00', '16:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-39', 'sub-gerente-diurno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE) REFEITORIO / VESTIARIO ORGANIZADO ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 39, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '09:00:00', '10:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-40', 'sub-gerente-diurno', 'GELADEIRAS ( SEM SACOLAS E PRODUTOS QUE POSSAM CONTAMILAR AS MARMITAS ) ?', 'ESTA TUDO OK NA RONDA ?', 'pendente', 40, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '10:00:00', '11:00:00', 5, 15, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-41', 'sub-gerente-diurno', 'VERIFICAR TODOS OS CONSULTA PREÇO', '1 FOTO DO TESTE OK  E 1 FOTO DO LOCAL QUE ESTA', 'pendente', 41, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:30:00', '08:30:00', 10, 20, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-42', 'sub-gerente-diurno', 'VERIFICAR TODOS OS CONSULTA PREÇO', '1 FOTO DO TESTE OK  E 1 FOTO DO LOCAL QUE ESTA', 'pendente', 42, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '14:00:00', '15:00:00', 10, 20, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-43', 'sub-gerente-diurno', 'HORARIO ALMOÇO', '1 INICIO E 1 NO TERMINO', 'pendente', 43, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '12:00:00', '13:00:00', 2, 2, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-44', 'sub-gerente-diurno', 'PAUSA CAFÉ', '1 INICIO E 1 NO TERMINO', 'pendente', 44, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '16:00:00', '16:30:00', 2, 2, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-45', 'sub-gerente-diurno', 'VERIFICAR PRECIFICAÇÃO DIA ANTERIOR ( OFERTA SEGUNDA FENOMENAL )', 'FOTO DE TODAS AS PLACAS  COLOCADA DA SEGUNDA FENOMENAL', 'pendente', 45, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '18:00:00', '19:00:00', 10, 20, '[]'::jsonb, 'semanal', '{0}', null),
  ('sub-gerente-diurno-46', 'sub-gerente-diurno', 'VERIFICAR PRECIFICAÇÃO ( OFERTA SEGUNDA FENOMENAL )', 'FOTO DE TODAS AS PLACAS  COLOCADA DA SEGUNDA FENOMENAL', 'pendente', 46, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:00:00', 10, 20, '[]'::jsonb, 'semanal', '{1}', null),
  ('sub-gerente-diurno-47', 'sub-gerente-diurno', 'VERIFICAR PRECIFICAÇÃO TERÇA E QUARTA VERDE , SE PERMANECE TODAS AS PLACAS OK ?', 'FOTO DE TODAS AS PLACAS', 'pendente', 47, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:30:00', 10, 20, '[]'::jsonb, 'semanal', '{2}', null),
  ('sub-gerente-diurno-48', 'sub-gerente-diurno', 'VERIFICAR PRECIFICAÇÃO TERÇA E QUARTA VERDE , SE PERMANECE TODAS AS PLACAS OK ?', 'FOTO DE TODAS AS PLACAS', 'pendente', 48, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:30:00', 10, 20, '[]'::jsonb, 'semanal', '{3}', null),
  ('sub-gerente-diurno-49', 'sub-gerente-diurno', 'VERIFICAR AS PRECIFICAÇÕES DO TABLOIDE DIA ANTERIOR ( SEGUNDA A QUINTA )', 'FOTO DE TODAS AS PLACAS', 'pendente', 49, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '18:00:00', '19:00:00', 20, 50, '[]'::jsonb, 'semanal', '{0}', null),
  ('sub-gerente-diurno-50', 'sub-gerente-diurno', 'VERIFICAR AS PRECIFICAÇÕES DO TABLOIDE ( SEGUNDA A QUINTA ), SE PERMANECE AS PLACAS OK ?', 'FOTO DE TODAS AS PLACAS', 'pendente', 50, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:30:00', 20, 50, '[]'::jsonb, 'semanal', '{0}', null),
  ('sub-gerente-diurno-51', 'sub-gerente-diurno', 'VERIFICAR AS PRECIFICAÇÕES DO TABLOIDE ( SEXTA , SABADO E DOMINGO ) , SE PERMANE AS PLACAS OK ?', 'FOTO DE TODAS AS PLACAS', 'pendente', 51, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:30:00', 20, 50, '[]'::jsonb, 'semanal', '{5,6,0}', null),
  ('sub-gerente-diurno-52', 'sub-gerente-diurno', 'VERIFICAR SE AS OFERTAS ESTÃO ENTRANDO CORRETAMENTE NOS PDV''S', 'TODAS AS OFERTAS ESTÃO ENTRANDO ? TODOS OS PDVS ?', 'pendente', 52, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '07:00:00', '08:00:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-53', 'sub-gerente-diurno', 'PONTO EXTRA ( AÇÕES SEGUNDA A QUINTA )', 'FOTO DOS PONTO EXTRA', 'pendente', 53, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '08:00:00', '18:00:00', 1, 10, '[]'::jsonb, 'semanal', '{0}', null),
  ('sub-gerente-diurno-54', 'sub-gerente-diurno', 'CONTROLE DE MARGEM DE VENDA', 'COMUNICAR COMERCIAL ( ESTANDO ALGO INRREGULAR)', 'pendente', 54, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '10:00:00', '11:00:00', 1, 1, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-55', 'sub-gerente-diurno', 'CONTROLAR TANQUE GERADOR', 'ENVIAR FOTO NA GERENCIA', 'pendente', 55, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '09:00:00', '10:00:00', 1, 1, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-56', 'sub-gerente-diurno', 'CONTROLAR MOTORES DAS GELADEIRAS EM GERAL', 'ENVIAR FOTO NA GERENCIA', 'pendente', 56, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '09:00:00', 1, 10, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-57', 'sub-gerente-diurno', 'SOLICITAR RETIRADAS DE CARRINHAS DO ESTACIONAMENTO E FRENTE DE LOJA', 'NOME DO COLABORADOR SOLICITADO PARA A RETIRA DOS CARRINHOS , FAZER  GIRO', 'pendente', 57, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '09:00:00', '10:00:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-58', 'sub-gerente-diurno', 'SOLICITAR RETIRADAS DE CARRINHAS DO ESTACIONAMENTO E FRENTE DE LOJA', 'NOME DO COLABORADOR SOLICITADO PARA A RETIRA DOS CARRINHOS , FAZER  GIRO', 'pendente', 58, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '10:00:00', '11:00:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-59', 'sub-gerente-diurno', 'SOLICITAR RETIRADAS DE CARRINHAS DO ESTACIONAMENTO E FRENTE DE LOJA', 'NOME DO COLABORADOR SOLICITADO PARA A RETIRA DOS CARRINHOS , FAZER  GIRO', 'pendente', 59, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '13:00:00', '14:00:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-60', 'sub-gerente-diurno', 'SOLICITAR RETIRADAS DE CARRINHAS DO ESTACIONAMENTO E FRENTE DE LOJA', 'NOME DO COLABORADOR SOLICITADO PARA A RETIRA DOS CARRINHOS , FAZER  GIRO', 'pendente', 60, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Tarde', '16:00:00', '17:00:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-61', 'sub-gerente-diurno', 'VERIFICAR ESTOQUE DOS AEREOS SE ESTÃO DATADOS E ORGANIADOS', 'ESTA TUDO DENTRO DOS CONFORMES ?', 'pendente', 61, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '08:00:00', '18:00:00', 10, 20, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-62', 'sub-gerente-diurno', 'VERIFICAÇÃO DE UTILIZAÇÃO DE TOCA , LUVA E EPIS NA PADARIA ( PESSOAL DA TARDE )', 'TUDO OK ?', 'pendente', 62, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:30:00', '08:30:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-63', 'sub-gerente-diurno', 'VERIFICAÇÃO DE LIMPEZA DOS UNIFORMES DA PADARIA  ( PESSOAL DA TARDE )', 'TUDO OK ?', 'pendente', 63, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:30:00', '08:30:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-64', 'sub-gerente-diurno', 'VERIFICAÇÃO DE UTILIZAÇÃO DE TOCA, LUVA E EPIS AÇOUGUE  ( PESSOAL DA TARDE )', 'TUDO OK ?', 'pendente', 64, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:30:00', '08:30:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-65', 'sub-gerente-diurno', 'VERIFICAÇÃO DE LIMPEZA DOS UNIFORMES AÇOUGUE ( PESSOAL DA TARDE )', 'TUDO OK ?', 'pendente', 65, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:30:00', '08:30:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-66', 'sub-gerente-diurno', 'BATIDA DE VALIDADE EM TODOS OS SETORES ( FAZER ACOMPANHAMENTO )', 'TUDO OK ?  ALGUM PRODUTO VENCIDO ?', 'pendente', 66, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '22:00:00', 0, null, '[]'::jsonb, 'semanal', '{2}', null),
  ('sub-gerente-diurno-67', 'sub-gerente-diurno', 'BATIDA DE PRECIFICAÇÃO EM TODOS OS SETORES ( FAZER ACOMPANHAMENTO )', 'TUDO OK ? ALGUMA DISCRIÇÃO ERRADA ? ALGUM PREÇO ERRADO ?', 'pendente', 67, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '22:00:00', 0, null, '[]'::jsonb, 'semanal', '{4}', null),
  ('sub-gerente-diurno-68', 'sub-gerente-diurno', 'ACOMPANHAR GRUPO DE RECEBIMENTO PARA MERCADORIA NÃO FICAR PARADA NO ESTOQUE', null, 'pendente', 68, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '18:00:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-69', 'sub-gerente-diurno', 'VERIFICAR SE O TIME DE SEGURANÇA ESTA FAZENDO A ROTINA CORRETA PARA PREVENÇÃO DE FURTO E ROUBO ( CHECK LIST E GRUPO NO WHATSAAP ).', null, 'pendente', 69, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '18:00:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-70', 'sub-gerente-diurno', 'VERIFICAR LIMPEZA DOS BANHEIROS', 'ESTA BEM LIMPO ? ESTAO SEGUINDO A ESCALA ?', 'pendente', 70, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '08:30:00', 2, 10, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-71', 'sub-gerente-diurno', 'VERIFICAR LIMPEZA DOS BANHEIROS', 'ESTA BEM LIMPO ? ESTAO SEGUINDO A ESCALA ?', 'pendente', 71, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '10:00:00', '11:00:00', 2, 10, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-72', 'sub-gerente-diurno', 'VERIFICAR LIMPEZA DOS BANHEIROS', 'ESTA BEM LIMPO ? ESTAO SEGUINDO A ESCALA ?', 'pendente', 72, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '15:00:00', '16:00:00', 2, 10, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-73', 'sub-gerente-diurno', 'VERIFICAR LIMPEZA DA LOJA', 'ESTA BEM LIMPA ? ESTÃO SEGUINDO A ESCALA ?', 'pendente', 73, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '10:00:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-74', 'sub-gerente-diurno', 'VERIFICAR LIMPEZA DA LOJA', 'ESTA BEM LIMPA ? ESTÃO SEGUINDO A ESCALA ?', 'pendente', 74, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Tarde', '11:00:00', '13:00:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-75', 'sub-gerente-diurno', 'VERIFICAR EXTINTORES ( VALIDADE , LACRE, LOCALIZAÇÃO ( DEIXAR SEMPRE LIVRE )', null, 'pendente', 75, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '10:00:00', '11:00:00', 0, null, '[]'::jsonb, 'mensal', '{}', '2026-09-10'),
  ('sub-gerente-diurno-76', 'sub-gerente-diurno', '( PRIMEIRO HORARIO )TIRAR RELATORIO DE MERCADORIAS RECEBIDAS NO DIA  ANTERIOR , E REPASSAR SE TUDO ESTA NA AREA DE VENDA', 'TODAS AS MERCADORIAS ESTAO NA AREA DE VENDA ?', 'pendente', 76, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '08:00:00', '18:00:00', 1, 2, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-77', 'sub-gerente-diurno', 'CONTAGEM FUNDO DE TROCO ( FISCAL) TODOS OS HORARIOS', 'ALGUMA FALTA NO FUNDO ? CONFIRMAR NOMES QUE FOI FEITA A CONFERENCIA', 'pendente', 77, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:00:00', '18:00:00', 0, null, '[]'::jsonb, 'semanal', '{5}', null),
  ('sub-gerente-diurno-78', 'sub-gerente-diurno', 'CONTROLE DE PRAGAS', 'CASO NÃO ESTEJA AVISAR GERENTE JULIANA', 'pendente', 78, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '08:00:00', '18:00:00', 1, 5, '[]'::jsonb, 'mensal', '{}', '2026-09-15'),
  ('sub-gerente-diurno-79', 'sub-gerente-diurno', 'EPIS ( HORARIO TARDE ) TODOS OS COLABORADORES ESTÃO OK ?', 'ESTÃO MARCANDO NO CONTROLE EPIS ?', 'pendente', 79, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:30:00', '08:30:00', 1, 5, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-80', 'sub-gerente-diurno', 'VENDAS FRENTE CAIXA ?', 'ESTÃO OFERENCENDO OS PRODUTOS ?', 'pendente', 80, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Manhã', '07:30:00', '18:00:00', 1, 5, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-diurno-81', 'sub-gerente-diurno', 'ESTÃO CONTROLANDO HORA EXTRA ? CASO PASSE DE 2 HORAS . PROGRAMAR PARA 2 HORAS E 15', '15 MINUTOS DE PAUSA BATIDA NO PONTO , FORNECER KIT HORA EXTRA PARA LANCHE', 'pendente', 81, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '07:30:00', '18:00:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null);


-- ----------------------------------------------------------------------------
-- Rotina 'sub-gerente-noturno' (24 atividades) — aba 'SUB GERENTE NOTURNO'
-- ----------------------------------------------------------------------------
insert into checklists (id, nome, ativo, reabre_automatico, reabre_intervalo_min, responsavel, corte_dia) values
  ('sub-gerente-noturno', 'Rotina completa ''Sub Gerente Noturno''', true, false, null, 'Sub Gerente Noturno', '07:00:00');
insert into checklist_items
  (id, checklist_id, titulo, detalhe, status, posicao,
   tipo_tarefa, resposta_opcoes, turno, horario_inicio, horario_termino,
   min_anexos, max_anexos, anexos, recorrencia, dias_semana, inicio)
values
  ('sub-gerente-noturno-1', 'sub-gerente-noturno', 'TIRAR FOTO DA RAMPA DE ENTRADA NO INICIO DO EXPEDIENTE', null, 'pendente', 1, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '20:00:00', '21:40:00', 1, 1, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-2', 'sub-gerente-noturno', 'TIRAR FOTO DA RAMPA NO TERMINO DE JORNADA', null, 'pendente', 2, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '05:50:00', '07:30:00', 1, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-3', 'sub-gerente-noturno', 'VERIFICAÇÃO DE EPIS DOS COLABORADORES ( LISTAGEM DO CONTROLE PREENCHIDA )', 'FOTO DO CONTROLE PREENCHIDA', 'pendente', 3, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '21:30:00', '22:00:00', 1, 1, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-4', 'sub-gerente-noturno', 'TEMPERATURA DAS GELADEIRAS', null, 'pendente', 4, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '21:30:00', '22:30:00', 1, 10, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-5', 'sub-gerente-noturno', 'TEMPERATURA DAS ILHAS', null, 'pendente', 5, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '21:30:00', '22:30:00', 1, 10, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-6', 'sub-gerente-noturno', 'TEMPERATURA DAS CAMARAS FRIA', null, 'pendente', 6, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '21:30:00', '22:30:00', 1, 10, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-7', 'sub-gerente-noturno', 'TEM SEGURANÇA DO NOTURNO ?', 'QUEM ? E QUANTOS ?', 'pendente', 7, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '21:30:00', '22:30:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-8', 'sub-gerente-noturno', 'FOTO DO ESTACIONAMENTO  ( SEM CARRO DE FUNCIONARIOS  )', 'TODOS OS ANGULOS', 'pendente', 8, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '21:30:00', '22:30:00', 1, 3, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-9', 'sub-gerente-noturno', 'FOTO DAS VAGAS EM FRENTES DA LOJA  ( SEM CARRO DE FUNCIONARIOS  )', 'TODOS OS ANGULOS', 'pendente', 9, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '21:30:00', '22:30:00', 1, 3, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-10', 'sub-gerente-noturno', 'GIRO LOJA ( VERIFICAR SE NÃO TEM NENHUMA INRREGULARIDADE)', null, 'pendente', 10, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '21:30:00', '22:30:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-11', 'sub-gerente-noturno', 'VERIFICAR TODOS OS CONSULTA PREÇO', '1 FOTO DO TESTE OK  E 1 FOTO DO LOCAL QUE ESTA', 'pendente', 11, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '05:00:00', '06:00:00', 1, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-12', 'sub-gerente-noturno', 'VERIFICAR TODOS OS CONSULTA PREÇO', '1 FOTO DO TESTE OK  E 1 FOTO DO LOCAL QUE ESTA', 'pendente', 12, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '05:00:00', '06:00:00', 1, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-13', 'sub-gerente-noturno', 'IMPRESSÃO DAS ETIQUETAS DE PREÇOS', '1 INICIO E 1 NO TERMINO', 'pendente', 13, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '00:30:00', '01:30:00', 2, 2, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-14', 'sub-gerente-noturno', 'PONTO EXTRA ( AÇÕES SEGUNDA A QUINTA )', 'FOTO DOS PONTO EXTRA', 'pendente', 14, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '21:30:00', '05:50:00', 1, 10, '[]'::jsonb, 'semanal', '{6}', null),
  ('sub-gerente-noturno-15', 'sub-gerente-noturno', 'PONTO EXTRA ( AÇÕES SEXTA A DOMINGO )', 'FOTO DOS PONTO EXTRA', 'pendente', 15, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '21:30:00', '05:50:00', 1, 10, '[]'::jsonb, 'semanal', '{4}', null),
  ('sub-gerente-noturno-16', 'sub-gerente-noturno', 'VERIFICAR SE O TIME ESTA FAZENDO A ROTINA CORRETA DA FUNÇAO ( TEMPO OCIOSO)', null, 'pendente', 16, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '22:00:00', '23:00:00', 1, 10, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-17', 'sub-gerente-noturno', 'VERIFICAR SE O TIME ESTA FAZENDO A ROTINA CORRETA DA FUNÇAO ( TEMPO OCIOSO)', null, 'pendente', 17, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Noite', '01:00:00', '02:00:00', 1, 10, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-18', 'sub-gerente-noturno', 'VERIFICAR SE O TIME ESTA FAZENDO A ROTINA CORRETA DA FUNÇAO ( TEMPO OCIOSO)', null, 'pendente', 18, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '04:00:00', '05:00:00', 1, 10, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-19', 'sub-gerente-noturno', 'VERIFICAR ESTOQUE DOS SETORES SE ESTA PADRÃO, ORGANIZADO E ALINHAR ESTRATEGIA DE ATUAÇÃO', null, 'pendente', 19, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '03:00:00', '04:00:00', 1, 10, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-20', 'sub-gerente-noturno', 'VERIFICAR SE O TIME DE SEGURANÇA ESTA FAZENDO A ROTINA CORRETA PARA PREVENÇÃO DE FURTO E ROUBO ( CHECK LIST E GRUPO NO WHATSAAP ).', null, 'pendente', 20, 'enquete', '["PADRÃO", "NÃO PADRÃO"]'::jsonb, 'Noite', '21:30:00', '05:50:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-21', 'sub-gerente-noturno', 'VERIFIQUE SE LIXO, PALETE, PAPELÃO E CARRINHO DA LIMPEZA FOI DIRECIONADO AO LOCAL CORRETO', null, 'pendente', 21, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '05:00:00', '05:50:00', 1, 50, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-22', 'sub-gerente-noturno', 'SINALIZAR SUB GERENTE DO DIURNO AS PENDENCIAS E PRIORIDADES DE REPOSIÇÃO', null, 'pendente', 22, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '05:00:00', '05:50:00', 0, null, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-23', 'sub-gerente-noturno', 'PORTAS GERAIS ( SE ESTAO TRANCADAS)', null, 'pendente', 23, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '05:30:00', '06:30:00', 1, 50, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null),
  ('sub-gerente-noturno-24', 'sub-gerente-noturno', 'DELISGAR EXAUSTORES , VENTILADORES , COMPUTADORES E LUZES.', null, 'pendente', 24, 'enquete', '["SIM", "NÃO"]'::jsonb, 'Manhã', '05:30:00', '06:30:00', 1, 20, '[]'::jsonb, 'semanal', '{0,1,2,3,4,5,6}', null);
